controller_manager:
  ros__parameters:
    update_rate: 150  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
 
    streaming_controller:
      type: position_controllers/JointGroupPositionController

    # mecanum_drive_controller:
    #   type: mecanum_drive_controller/MecanumDriveController

joint_state_broadcaster:
  ros__parameters:

    joints: 
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    extra_joints:
      - joint_wheel_front_left
      - joint_wheel_front_right
      - joint_wheel_back_left
      - joint_wheel_back_right

streaming_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position

joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.0
      joint1: {trajectory: 1.0, goal: 0.01}
      joint2: {trajectory: 1.0, goal: 0.01}
      joint3: {trajectory: 1.0, goal: 0.01}
      joint4: {trajectory: 1.0, goal: 0.01}
      joint5: {trajectory: 1.0, goal: 0.01}
      joint6: {trajectory: 1.0, goal: 0.01}
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0

# mecanum_drive_controller:
#   ros__parameters:
#     reference_timeout: 1.0 # max time between command messages before the vehicle should stop
#     front_left_wheel_command_joint_name: "front_left_wheel_joint"
#     front_right_wheel_command_joint_name: "front_right_wheel_joint"
#     rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
#     rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
#     kinematics:
#         base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
#         wheels_radius: 0.3
#         sum_of_robot_center_projection_on_X_Y_axis: 1.1
#     base_frame_id: "base_link"
#     odom_frame_id: "odom"
#     enable_odom_tf: true
    