# This format is suitable for the following services
#   - clean_error
#   - clean_warn
#   - clean_conf
#   - save_conf
#   - reload_dynamics
#   - set_counter_reset
#   - set_counter_increase
#   - clean_gripper_error
#   - clean_bio_gripper_error
#   - start_record_trajectory
#   - stop_record_trajectory
#   - ft_sensor_set_zero
#   - set_linear_track_stop
#   - clean_linear_track_error
#   - open_lite6_gripper
#   - close_lite6_gripper
#   - stop_lite6_gripper

---

int32 ret
string message
