# This format is suitable for the following services
#   - set_impedance
#   - set_impedance_mbk
#   - set_impedance_config

#   - set_impedance
#   - set_impedance_config
int16 coord
int16[] c_axis

#   - set_impedance
#   - set_impedance_mbk
float32[] m
float32[] k
float32[] b

---

int16 ret
string message