# This format is suitable for the following services
#   - get_state
#   - get_cmdnum
#   - get_vacuum_gripper
#   - get_gripper_err_code
#   - get_bio_gripper_status
#   - get_bio_gripper_error
#   - get_reduced_mode
#   - get_report_tau_or_i
#   - ft_sensor_app_get
#   - get_ft_sensor_error
#   - get_trajectory_rw_status
#   - get_linear_track_pos
#   - get_linear_track_status
#   - get_linear_track_error
#   - get_linear_track_is_enabled
#   - get_linear_track_on_zero
#   - get_linear_track_sci

---

int16 ret
string message

int16 data
