# This format is suitable for the following services
#   - set_gravity_direction
#   - set_tcp_offset
#   - set_world_offset
#   - set_reduced_joint_range

float32[] datas

---

int16 ret
string message
