# This format is suitable for the following services
#   - set_tgpio_modbus_timeout

# set the timeout parameter in modbus communication, in milliseconds
int32 timeout

# whether the set timeout is the timeout of transparent transmission
bool is_transparent_transmission false

---

int16 ret
string message
